### ISSUE TITLE
error on cleanup when some file has filenames starting with zeros 

### ISSUE THREAD

**Issue by vinodkurienalex** [gpbl/webpack-cleanup-plugin#31]
getting error on cleanup ...

The actual ttf file exists and is a reference in a CSS.. with name '00ef8df54d2b9c8e232dd8970b64b0fc.ttf'

i think the plugin ignores the preceding zeros in filename ?
```
Error: ENOENT: no such file or directory, unlink 'D:\Web\build\generated\ef8df54d2b9c8e232dd8970b64b0fc.ttf'
    at Error (native)
    at fs.unlinkSync (fs.js:980:18)
    at Array.forEach (native)
    at Compiler.<anonymous> (D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\webpack-cleanup-plugin\lib\WebpackCleanupPlugin.js:55:17)
    at Compiler.applyPlugins (D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\tapable\lib\Tapable.js:26:37)
    at Watching._done (D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\webpack\lib\Compiler.js:78:17)
    at Watching.<anonymous> (D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\webpack\lib\Compiler.js:61:18)
    at Compiler.emitRecords (D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\webpack\lib\Compiler.js:282:37)
    at Watching.<anonymous> (D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\webpack\lib\Compiler.js:58:19)
    at D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\webpack\lib\Compiler.js:275:11
    at Compiler.applyPluginsAsync (D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\tapable\lib\Tapable.js:60:69)
    at Compiler.afterEmit (D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\webpack\lib\Compiler.js:272:8)
    at Compiler.<anonymous> (D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\webpack\lib\Compiler.js:267:14)
    at D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\async\lib\async.js:52:16
    at done (D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\async\lib\async.js:246:17)
    at D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\async\lib\async.js:44:16
    at D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\less\node_modules\graceful-fs\graceful-fs.js:43:10
    at D:\VSO\Assessor3.Web\Assessor3.Web\node_modules\enhanced-resolve\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by gpbl** [comment]
This seems a lot likes the issues we were trying to solve with the last releases 😭 
I can't help testing or supporting Windows, sorry. Which version of node are you using? Could you try from a path not containing dots in it?

**Comment by vinodkurienalex** [comment]
ok.. issue is with dots is it?
I am using node v5.3.0 in Windows 8.1
Will have to try other ways to cleanup.. then. Thanks for the reply
